// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN8QIimpDldpXDYXmq4QnfmN_Kpo_cqY0',
    appId: '1:330756045382:web:fc6520b5625b1f7feaa847',
    messagingSenderId: '330756045382',
    projectId: 'application029-2024',
    authDomain: 'application029-2024.firebaseapp.com',
    storageBucket: 'application029-2024.appspot.com',
    measurementId: 'G-CHZ28YYT0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMGxn-y3t22fHBV3m7C_Y15jIW0iJiqNk',
    appId: '1:330756045382:android:76a5be42f81b8368eaa847',
    messagingSenderId: '330756045382',
    projectId: 'application029-2024',
    storageBucket: 'application029-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2Kqk4a-HtDTz6qir3yjH3sNB-i4b6ZN4',
    appId: '1:330756045382:ios:f900ef876bddcea2eaa847',
    messagingSenderId: '330756045382',
    projectId: 'application029-2024',
    storageBucket: 'application029-2024.appspot.com',
    iosBundleId: 'com.example.tradingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2Kqk4a-HtDTz6qir3yjH3sNB-i4b6ZN4',
    appId: '1:330756045382:ios:ee8a3a0e9774e9c5eaa847',
    messagingSenderId: '330756045382',
    projectId: 'application029-2024',
    storageBucket: 'application029-2024.appspot.com',
    iosBundleId: 'com.example.tradingApp.RunnerTests',
  );
}
