// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5QOsKB0NzTHg06UO52E0aYEmrCJqwl0w',
    appId: '1:644404952965:web:9bc729baebe1c716a2ceec',
    messagingSenderId: '644404952965',
    projectId: 'firbase-app-029',
    authDomain: 'firbase-app-029.firebaseapp.com',
    databaseURL: 'https://firbase-app-029-default-rtdb.firebaseio.com',
    storageBucket: 'firbase-app-029.appspot.com',
    measurementId: 'G-GFZHRCVS2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6T4vMjRB1Ix511vhgSIHLBY8nhA8h0iA',
    appId: '1:644404952965:android:465b52b27ddeb47ba2ceec',
    messagingSenderId: '644404952965',
    projectId: 'firbase-app-029',
    databaseURL: 'https://firbase-app-029-default-rtdb.firebaseio.com',
    storageBucket: 'firbase-app-029.appspot.com',
  );
}
